name: github pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: fabasoad/setup-mint-action@main
      - name: Build Mint
        run: cd workspace && mint build

      - name: Add 'onovomercado-widgets/' to index.html URLs 
        uses: mingjun97/file-regex-replace
        with:
          regex: 'src="index.js"'
          replacement: 'src="onovomercado-widgets/index.js"'
          flags: "g"                  # Optional, defaults to "g"
          include: 'dist/index.html'    # Optional, defaults to ".*"
          exclude: '.^'               # Optional, defaults to '.^'
          encoding: 'utf8'            # Optional, defaults to 'utf8'
          path: '.'                   # Optional, defaults to '.'
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./workspace/dist