name: github pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: fabasoad/setup-mint-action@main
      - name: Build Mint
        run: cd workspace && mint build

      - name: Add "/onovomercado-widgets" to att src on script
        uses: mingjun97/file-regex-replace
        with:
          regex: 'src="/index.js"'
          replacement: 'src="/onovomercado-widgets/index.js"'
          include: 'index.html'

      - name: Modify version number
        uses: mingjun97/file-regex-replace
        with:
          regex: 'href="(?!http)'
          replacement: 'href="onovomercado-widgets/'
          include: 'index.html'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./workspace/dist